# This is a generated file. Not intended for manual editing.
services:
  devhabit.api:
    build:
      context: "C:\\Users\\suare\\DEV\\PragmaticApiRest\\DevHabit"
      dockerfile: "DevHabit.Api/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57400"
    - "--timeout=60"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "devhabitapi:dev"
    ports:
    - "127.0.0.1:57003:57000"
    - "127.0.0.1:57203:57200"
    - "127.0.0.1:57403:57400"
    volumes:
    - "C:\\Users\\suare\\DEV\\PragmaticApiRest\\DevHabit\\DevHabit.Api:/app:rw"
    - "C:\\Users\\suare\\DEV\\PragmaticApiRest\\DevHabit:/src:rw"
    - "C:\\Users\\suare\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\Users\\suare\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2024.3.6\\\
      Linux64:/opt/JetBrains/RiderDebuggerTools"
    - "C:\\Program Files\\JetBrains\\JetBrains Rider 2024.3.6\\bin\\backend-log.xml:/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    - "C:\\Users\\suare\\AppData\\Local\\JetBrains\\Rider2024.3\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2025_3_30_07_06_37:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app"
